<a href="https://colab.research.google.com/github/imamfirdaus-if/Image-compression-using-huffman-coding/blob/main/Kompresi_gambar_menggunakan_Huffman_coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
#Import Library yang diperlukan
import re
import numpy as np
from PIL import Image

#Masukkan jenis gambar dan nama file yang akan diuji
print("==========================================")
print("Kompresi gambar menggunakan Huffman coding")
print("==========================================")
print("Jenis gambar yang bisa diterima")
print("1. Gambar berwarna")
print("2. Gambar hitam putih")
h = int(input("Masukkan jenis gambar yang akan diuji (1 atau 2): "))
#Kondisi jika nama file yang dimasukkan jenis gambar berwarna
if h == 1:
    file = input("Masukkan Nama File yang akan diuji: ")
    my_string = np.asarray(Image.open(file),np.uint8)
    shape = my_string.shape
    a = my_string
    print ("String yang dimasukkan adalah: ")
    print (my_string)
    my_string = str(my_string.tolist())
#Kondisi jika nama file yang dimasukkan jenis gambar hitam putih
elif h == 2:
    array = np.arange(0, 737280, 1, np.uint8)
    my_string = np.reshape(array, (1024, 720))
    print ("String yang dimasukkan adalah:",my_string)
    a = my_string
    my_string = str(my_string.tolist())
#Kondisi jika nama file yang dimasukkan salah
else:
    print("Nama file yang Anda masukkan salah, silahkan cek kembali nama file yang dimaksud")

#Frequensi setiap pengulangan huruf
letters = []
only_letters = []
for letter in my_string:
    if letter not in letters:
        frequency = my_string.count(letter)
        letters.append(frequency)
        letters.append(letter)
        only_letters.append(letter)

#Mengurutkan menurut frequensi
nodes = []
while len(letters) > 0:
    nodes.append(letters[0:2])
    letters = letters[2:]
nodes.sort()
huffman_tree = []
huffman_tree.append(nodes)

def combine_nodes(nodes):
    pos = 0
    newnode = []
    if len(nodes) > 1:
        nodes.sort()
        #Menetapkan nilai 1 dan 0
        nodes[pos].append("1")
        nodes[pos+1].append("0")
        combined_node1 = (nodes[pos] [0] + nodes[pos+1] [0])
        combined_node2 = (nodes[pos] [1] + nodes[pos+1] [1])
        #menggabungkan node
        newnode.append(combined_node1)
        newnode.append(combined_node2)
        newnodes=[]
        newnodes.append(newnode)
        newnodes = newnodes + nodes[2:]
        nodes = newnodes
        huffman_tree.append(nodes)
        combine_nodes(nodes)
    return huffman_tree                                    

newnodes = combine_nodes(nodes)

huffman_tree.sort(reverse = True)
print("Huffman Tree dengan gabungan path:")

checklist = []
for level in huffman_tree:
    for node in level:
        if node not in checklist:
            checklist.append(node)
        else:
            level.remove(node)

#Mencetak Huffman Tree
count = 0
for level in huffman_tree:
    print("Level", count,":",level)            
    count+=1
print()

#Mencetak Kode Biner
letter_binary = []
if len(only_letters) == 1:
    lettercode = [only_letters[0], "0"]
    letter_binary.append(letter_code*len(my_string))
else:
    for letter in only_letters:
        code =""
        for node in checklist:
            if len (node)>2 and letter in node[1]:           
                code = code + node[2]
        lettercode =[letter,code]
        letter_binary.append(lettercode)
print(letter_binary)
print("Binary code hasil generate:")
for letter in letter_binary:
    print(letter[0], letter[1])

bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring

#Menampilkan hasil dari Kompresi gambar menggunakan Huffman coding
uncompressed_file_size = len(my_string)*7
compressed_file_size = len(binary)-2
print("Ukuran asli dari file ini adalah ", uncompressed_file_size,"bits")
print("Ukuran setelah di kompres dari file ini adalah ", compressed_file_size,"bits")
print("Selisih ukuran file asli dengan file hasil kompres adalah ",uncompressed_file_size-compressed_file_size,"bits")
hasil = input("Masukkan Nama File hasil kompres (contoh: kompres.txt): ")
output = open(hasil,"w+")
print("File kompresi yang dihasilkan menjadi", hasil)
output = open(hasil,"w+")
print("Silahkan tunggu proses penguraian kode (Decodig)")
output.write(bitstring)

bitstring = str(binary[2:])
uncompressed_string =""
code =""
for digit in bitstring:
    code = code+digit
    pos=0
    for letter in letter_binary:
        if code ==letter[1]:
            uncompressed_string=uncompressed_string+letter_binary[pos] [0]
            code=""
        pos+=1

if h == 1:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, shape)
    print(res)
    print("Pengujian dari bentuk dan array yang dihasilkan")
    print("Dimensi gambar yang dimasukkan:",shape)
    print("Dimensi gambar yang dihasilkan:",res.shape)
    data = Image.fromarray(res)
    #namafile = input("Masukkan Nama File yang diuji: ")
    data.save(file)
    if a.all() == res.all():
        print("Proses kompresi gambar berhasil")
if h == 2:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    print(res)
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, (1024, 720))
    print(res)
    data = Image.fromarray(res)
    #namafile = input("Masukkan Nama File yang diuji: ")
    data.save(file)
    print("Proses Kompresi Gambar berhasil")

Kompresi gambar menggunakan Huffman coding
Jenis gambar yang bisa diterima
1. Gambar berwarna
2. Gambar hitam putih
Masukkan jenis gambar yang akan diuji (1 atau 2): 1
Masukkan Nama File yang akan diuji: Nocturnal.tiff
String yang dimasukkan adalah: 
[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 ...

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 25